-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 02:09:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema xqsrd_cy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xqsrd_cy` ;

-- -----------------------------------------------------
-- Schema xqsrd_cy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xqsrd_cy` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `xqsrd_cy` ;

-- -----------------------------------------------------
-- Table `cy_website_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cy_website_account` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cy_website_account` (
  `id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一性主键，自增1',
  `website_name` CHAR(32) NULL DEFAULT NULL COMMENT '网站名称',
  `website_url` CHAR(32) NULL DEFAULT NULL COMMENT '网站地址',
  `login_name` CHAR(32) NOT NULL COMMENT '用户名',
  `login_passwd` CHAR(255) NOT NULL COMMENT '登录密码',
  `bind_mail` CHAR(32) NULL DEFAULT NULL COMMENT '绑定邮箱',
  `bind_phone` CHAR(11) NULL DEFAULT NULL COMMENT '绑定手机',
  `disc` VARCHAR(255) NULL DEFAULT NULL COMMENT '描述',
  `gmt_create` DATETIME NULL DEFAULT NULL COMMENT '创建日期',
  `gmt_modified` DATETIME NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '网站账号保存表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_user` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `login_name` VARCHAR(64) NULL COMMENT '登录名',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `username` VARCHAR(64) NOT NULL COMMENT '用户名',
  `mobile` VARCHAR(20) NULL COMMENT '手机',
  `email` VARCHAR(64) NULL COMMENT '邮箱',
  `login_time` DATETIME NULL COMMENT '登录时间',
  `last_login_time` DATETIME NULL COMMENT '上次登录时间',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`xid`))
ENGINE = InnoDB
COMMENT = '用户表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_template` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_template` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`xid`))
ENGINE = InnoDB
COMMENT = '模板表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_role` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `role_name` VARCHAR(32) NULL,
  `role_description` VARCHAR(256) NULL COMMENT '角色描述',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`xid`))
ENGINE = InnoDB
COMMENT = '角色表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_permission` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_permission` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `permission_name` VARCHAR(64) NULL COMMENT '权限名称',
  `permission_description` VARCHAR(256) NULL COMMENT '权限描述',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`xid`))
ENGINE = InnoDB
COMMENT = '权限表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_user_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_user_role` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `x_user_id` BIGINT UNSIGNED NULL COMMENT '用户id',
  `x_role_id` BIGINT UNSIGNED NULL COMMENT '角色id',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`xid`),
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`x_role_id`)
    REFERENCES `x_role` (`xid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`x_user_id`)
    REFERENCES `x_user` (`xid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户角色表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_role_permission` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_role_permission` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  `x_role_id` BIGINT UNSIGNED NULL,
  `x_permission_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`xid`),
  CONSTRAINT `fk_role_id2`
    FOREIGN KEY (`x_role_id`)
    REFERENCES `x_role` (`xid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_id`
    FOREIGN KEY (`x_permission_id`)
    REFERENCES `x_permission` (`xid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '模板表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_menu` (
  `xid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  `menu_path` VARCHAR(32) NOT NULL COMMENT '路由路径，权限名称',
  `menu_component` VARCHAR(128) NOT NULL COMMENT '实际页面路径',
  `menu_icon` VARCHAR(45) NULL COMMENT '菜单图标',
  `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父节点id',
  `pos` VARCHAR(32) NULL COMMENT '排序权重',
  PRIMARY KEY (`xid`))
ENGINE = InnoDB
COMMENT = '模板表';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
